# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	# Every Vagrant virtual environment requires a box to build off of.
	config.vm.box = "hashicorp/precise32"
	
	# Create a forwarded port mapping which allows access to a specific port
	# within the machine from a port on the host machine. In the example below,
	# accessing "localhost:8080" will access port 80 on the guest machine.
	# config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network :forwarded_port, guest: 6627, host: 6627   # storm Nimbus Thrift port 
    config.vm.network :forwarded_port, guest: 7777, host: 7777   # storm UI
    config.vm.network :forwarded_port, guest: 2181, host: 2181   # zk
    config.vm.network :forwarded_port, guest: 7000, host: 7000   # Cassandra cluster
    config.vm.network :forwarded_port, guest: 9160, host: 9160   # Cassandra Thrift client
    config.vm.network :forwarded_port, guest: 9042, host: 9042   # Cassandra CQL client
    config.vm.network :forwarded_port, guest: 7199, host: 7199   # Cassandra jmx
 
 
	# Set virtual machine memory size
	config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end 
 
	# for vagrant < 1.7
	config.vm.provision "shell", path: "bootstrap-once.sh"
	config.vm.provision "shell", path: "bootstrap-always.sh", run: "always"
	# for vagrant > 1.7
	#config.vm.provision "bootstrap-once", type: "shell", path: "bootstrap-once.sh"
	#config.vm.provision "bootstrap-always", type: "shell", path: "bootstrap-always.sh", run: "always"
 
end
